# Generated by Django 5.2.4 on 2025-07-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
